volumes:
  cloud-infra-with-aws__database-data-dev:

networks:
  cloud-infra-with-aws__network-dev:
    driver: bridge

services:
  app:
    container_name: cloud-infra-with-aws__app-dev
    image: cloud-infra-with-aws__app-image-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3010:3000 # server
      - 5555:5555 # prisma studio
    environment:
      - DATABASE_URL=postgresql://cloud-infra-with-aws__db-user-dev:12345678@cloud-infra-with-aws__db-dev:5432/cloud-infra-with-aws__db-name-dev?schema=public
    networks:
      - cloud-infra-with-aws__network-dev
    develop:
      watch:
        - action: sync
          path: ./build
          target: /app/build
        - action: sync
          path: ./prisma
          target: /app/prisma
        - action: rebuild
          path: package.json

  database:
    container_name: cloud-infra-with-aws__db-dev
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=cloud-infra-with-aws__db-user-dev
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=cloud-infra-with-aws__db-name-dev
    ports:
      - 5432:5432 # db
    volumes:
      - cloud-infra-with-aws__database-data-dev:/var/lib/postgresql/data
    networks:
      - cloud-infra-with-aws__network-dev