volumes:
  cloud-infra-with-aws__database-data-dev:

networks:
  cloud-infra-with-aws__network-dev:
    driver: bridge

services:
  app:
    container_name: cloud-infra-with-aws__app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT_DEV}:3000
      - ${PRISMA_STUDIO_PORT_DEV}:5555
    networks:
      - cloud-infra-with-aws__network-dev
    develop:
      watch:
        - action: sync
          path: ./build
          target: /app/build
        - action: sync
          path: ./prisma
          target: /app/prisma
        - action: rebuild
          path: package.json

  database:
    container_name: cloud-infra-with-aws__db-dev
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER_DEV}
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
      - POSTGRES_DB=${DB_NAME_DEV}
    ports:
      - ${DB_PORT_DEV}:5432
    volumes:
      - cloud-infra-with-aws__database-data-dev:/var/lib/postgresql/data
    networks:
      - cloud-infra-with-aws__network-dev