volumes:
  cloud-infra-with-aws__database-data-prod:

networks:
  cloud-infra-with-aws__network-prod:
    driver: bridge

services:
  app:
    container_name: cloud-infra-with-aws__app-prod
    image: cloud-infra-with-aws__app-image-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # http server
    env_file:
      - ./.env.prod
    networks:
      - cloud-infra-with-aws__network-prod

  database:
    container_name: ${DATABASE_HOST}
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - 5432:5432 # db
    volumes:
      - cloud-infra-with-aws__database-data-prod:/var/lib/postgresql/data
    networks:
      - cloud-infra-with-aws__network-prod
