# @IP=54.166.180.168
@IP=host.docker.internal
@PORT=3010
# @PORT=3000

@baseUrl=http://{{IP}}:{{PORT}}

###
# Healthcheck
GET {{baseUrl}}/system/healthcheck

###
# Create user
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "email@emailcom",
  "username": "user",
  "nickname": "nick",
  "password": "123456"
}

###
# Login
# @name login
POST {{baseUrl}}/session/login
Content-Type: application/json

{
  "email": "email@emailcom",
  "password": "123456"
}

###
# Get all users
@authToken = {{login.response.body.token}}
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###
# Get user by id
@userId = {{createUser.response.body.userId}}
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}