# ports: dev 3010, prod 3000

@PORT=3000
@USER_ID=

###
GET http://host.docker.internal:{{PORT}}/healthcheck

###
GET http://host.docker.internal:{{PORT}}/users

###
GET http://host.docker.internal:{{PORT}}/users/{{USER_ID}}

###
POST http://host.docker.internal:{{PORT}}/users
Content-Type: application/json

{
  "email": "email@emailcom",
  "username": "username",
  "nickname": "nickname",
  "password": "1q2w3e4r5t"
}