name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL_TEST: file:../tests/db/dev.db

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Installing dependencies
        run: npm install

      - name: Running coverage tests
        run: npm run test:coverage
