name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Installing dependencies
        run: npm install

      - name: Run tests
        run: |
          npm run update:test-db-schema
          npm run test:coverage
